<?php
/**
 *  @file
 *  Main file for custom hooks and functions
 */
/**
 * Implements hook_theme().
 */
  function jek_12_theme($existing, $type, $theme, $path): array {
    return [
      'test' => [
        'variables' => [
          'hi_text' => NULL,
          'form' => [],
          'rowsArr' => [],
          'rowQuantity' => NULL,
        ],
      ],
      'about' => [
        'variables' => [
          'rowsArr' => [],
          'rowQuantity' => NULL,
        ],
      ],
    ];
  }
//  function jek_12_preprocess_node__page(array &$variables) : void {
//    //Module name: 'mymodule', library name: 'mymodule'.
//    $variables['#attached']['library'][] = 'jek_12/custom_libs';
//  }
