<?php
/**
 *  @file
 *  Main file for custom hooks and functions
 */
/**
 * Implements hook_theme().
 */
  function jek_12_theme($existing, $type, $theme, $path): array {
    return [
      'test' => [
        'variables' => ['hi_text' => NULL, 'date'],
      ],
    ];
  }

  /**
   * Implements template_preprocess_HOOK() for test.
   */
  function template_preprocess_test(&$variables): void {
    $time = Drupal::time()->getCurrentTime();
    $date_formatter = Drupal::service('date.formatter');
    $variables['date'] = $date_formatter->format($time, 'short');
  }

